"""Adicionar data_de_nascimento na tabela usuarios

Revision ID: 02fe17f8a65e
Revises: 477386131f6f
Create Date: 2025-12-01 21:29:35.829542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fe17f8a65e'
down_revision: Union[str, Sequence[str], None] = '477386131f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('data_de_nascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'data_de_nascimento')
    # ### end Alembic commands ###
